name: Build and run

on:
  schedule:
    - cron: "23 * * * *" # Every 30 mins
  push:
    branches: [main, rate-limit-workaround]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: signal-cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn test
      - run: yarn build
      # From here we only run if on main branch
      - if: github.ref == 'refs/heads/rate-limit-workaround'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
      - if: github.ref == 'refs/heads/rate-limit-workaround'
        run: curl -L "https://github.com/AsamK/signal-cli/releases/download/v0.10.8/signal-cli-0.10.8-Linux.tar.gz" | tar -zx
      - if: github.ref == 'refs/heads/rate-limit-workaround'
        run: echo "RANDOM_SUFFIX=${RANDOM}${RANDOM}" >> $GITHUB_ENV
      - if: github.ref == 'refs/heads/rate-limit-workaround'
        uses: actions/cache@v3
        with:
          path: .signal-cli-data
          key: signal-cli-data-${{ env.RANDOM_SUFFIX }}
          restore-keys: |
            signal-cli-data-
      - if: github.ref == 'refs/heads/rate-limit-workaround'
        run: yarn start
        env:
          DRY_RUN: "true"
          ACTIVITIES_ENABLED: "false"
          SIGNAL_USER: ${{ secrets.SIGNAL_USER }}
          MYCLUBHOUSE_ACCESS_TOKEN: ${{ secrets.MYCLUBHOUSE_ACCESS_TOKEN }}
